apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ok-api
  template:
    metadata:
      labels:
        service: ok-api
    spec:
      containers:
        - name: ok-api-service
          image: dan551/cpp
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: ok-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
